# To install jekyll framework.

FROM ubuntu:latest

MAINTAINER Inderpal Singh <inderpal2406@gmail.com>

ENV REFRESHED_AT 06-01-2020_13:00_UTC

RUN apt-get update && \
    apt-get install -y ruby ruby-dev build-essential nodejs
