version: '3'

services:
  web:
    build: .
    image: inderpal2406/web:v0.0.5
    ports:
      - "5000:5000"
    volumes:
      - .:/code
      - logvolume01:/var/log
    links:
      - redis
  redis:
    image: redis
    volumes:
      - logvolume01: {}
