version: '3.1'
services:
  webserver:
    image: nginx:alpine
    container_name: web
    restart: unless_stopped
    ports:
      - "80:80"
      - "443:443"
  dbserver:
    image: mysql:5.7
    container_name: db
    restart: unless_stopped
    ports:
      - "3306:3306"
  backend:
    image: redis
    container_name: redis
    restart: unless_stopped
    ports:
      - "6379:6379"
